### ISSUE TITLE
Number Pairs main checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-pairs#1]
# Number Pairs main checklist

## Design

- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback**
  - [ ] ~~*If a Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)~~
  - [x] *If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Prototype items**
  - [ ] Auxiliary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Send Simulation Notification from the Admin page (to alert translators)
- [ ] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (
    see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [ ] [Draft the Email announcement language](https://github.com/phetsims/tasks/issues/new?assignees=&labels=tasks%3Aemail&projects=&template=sim-announcement-email.md&title=Sim+Announcement+Email)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website**
  - [ ] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities. For appropriate activities, tag the HTML5 version and UNTAG the deprecated version.
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [ ] Hold postmortem if applicable (Date: //)
  - [ ] Send Simulation Notification from the Admin page (to alert translators)

## Inclusive Features

- [ ] Alternative Input (Started: ) (Completed: )
  - [x] Organize interactions in the order of pedagogical importance within the PDOM's Play Area and Control Area.
  - [x] Create screen-specific [Keyboard Shortcuts dialogs](https://docs.google.com/document/d/1cBnuLYYFb6d3eyJlVzjEz9sp2XlAI8upWXUUrcyHu4c/edit). [Ai template](https://o365coloradoedu.sharepoint.com/:u:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Design%20Resources/Design%20Resources%20-%20Sim%20Design/Keyboard%20Dialog%20Template.ai?csf=1&web=1&e=th8xeg)
- [ ] Sound & ~~Sonification~~ (Completed: )
  - [ ] Sound design requirements determined: date: //
  - [ ] Sound design complete: date: //
  - [ ] UI Sounds implemented: date: //
  - [ ] All sounds implemented: date: //
- [ ] ~~Essential Description~~
  - [ ] Accessible names implemented: date: //
- [ ] ~~Interactive Description~~ - (link to description design & implementation checklist)
  - [ ] Description design complete (Started: ) (Completed: )
  - [ ] Development complete (Started: ) (Completed: )
  - [ ] Mobile description included
- [ ] ~~Voicing~~ - (include links to relevant voicing design document)

## Implementation

- [x] **Repository created** by
  following [new-repo-checklist.md](https://github.com/phetsims/phet-info/blob/main/checklists/new-repo-checklist.md) (
  Date: 7/23/24)
- [x] **Development started** (Date: //)
- [x] **Sim is "feature complete"** (Date: //)
- [ ] **QA team "first look"** (Date: //)
- [x] Interviews may happen around here (see above)
- [x] **Sim team sign-off** (Date: //)
- [ ] **Code review completed** (Date: //)
- [ ] **Sim dev test completed** (Date: //)
- [ ] **Sim RC tests completed** (Date: //)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/main/js/CreditsNode.js))
  - [x] Add CT tests for public query parameters that need testing. See examples
    in [listContinuousTests.js](https://github.com/phetsims/perennial/blob/main/js/listContinuousTests.js)
- [x] **Published** (Date: //)

## QA

- [ ] ~~*If a Port:* **Legacy sim tested for bugs**; issues reported in repo~~
- [x] **Dev testing started** (Date: //)
- [x] **Dev testing completed** (Date: //)
- [x] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: //)
